name: Release
on:
  push:
    tags:
      - 'v[0-9]+.[0-9]+.[0-9]+'

permissions:
  contents: write

jobs:
  release:
    name: Release
    strategy:
      matrix:
        kind: ['Linux', 'Windows', 'MacOS']
        include:
          - kind: 'Linux'
            os: ubuntu-latest
          - kind: 'Windows'
            os: windows-latest
          - kind: 'MacOS'
            os: macos-latest
    runs-on: ${{ matrix.os }}
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Install dependencies
        run: |
          sudo apt-get install -y \
            build-essential \

      - name: Build
        run: |
          cmake -S . -B build -DCMAKE_BUILD_TYPE=Release
          cmake --build build --config Release
          zip -r I3T-${{ matrix.kind }}-${{ steps.version.outputs.version }}.zip .

      - name: Publish
        uses: softprops/action-gh-release@v1
        with:
          files: "I3T*.zip"
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
