name: Release
on:
  push:
    tags:
      - 'v[0-9]+.[0-9]+.[0-9]+'

permissions:
  contents: write

jobs:
  release:
    name: Release
    strategy:
      matrix:
        kind: ['Linux', 'Windows', 'MacOS']
        include:
          - kind: 'Linux'
            os: ubuntu-latest
          - kind: 'Windows'
            os: windows-latest
          - kind: 'MacOS'
            os: macos-latest
    runs-on: ${{ matrix.os }}
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Install Linux dependencies
        if: matrix.kind == 'Linux'
        run: |
          sudo apt-get install -y build-essential \

      - name: Build and create archive
        shell: bash
        run: |
          cmake -S . -B build -DCMAKE_BUILD_TYPE=Release
          cmake --build build --config Release
          if [ "${{ matrix.target }}" == "win-x64" ]; then
            7z a -tzip I3T-${{ matrix.kind }}.zip build/HelloWorld*
          else
            zip -r I3T-${{ matrix.kind }}.zip LICENCE build/HelloWorld*
          fi

      - name: Publish
        uses: softprops/action-gh-release@v1
        with:
          draft: true
          files: "I3T*.zip"
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
